#%RAML 1.0 DataType
description: dt-create-users
properties:
  name:
    type: string
    description: Name from user
    minLength: 1
    maxLength: 50
    example: "Juan Manuel"
  lastName:
    type: string
    description: Last name from user
    minLength: 1
    maxLength: 50
    example: "Luzzi"
  email:
    type: string
    pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$
    description: A valid email address
    example: "luzzijuanma@gmail.com"
  phoneNumber:
    type: string
    description: phoneNumber from user (6 to 12 digits)
    example: "5491165912727"
    pattern: ^\d{6,13}$
  city:
    type: string
    description: City where the user lives
    minLength: 1
    maxLength: 100
    example: "Buenos Aires"
  
  
  
